# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 40, 512, 448))
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setObjectName("graphicsView")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(530, 10, 341, 481))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.status.setFont(font)
        self.status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.status.setObjectName("status")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 511, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.preview = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.preview.setObjectName("preview")
        self.horizontalLayout_2.addWidget(self.preview)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 500, 211, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.connectButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.connectButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setMinimumSize(QtCore.QSize(0, 0))
        self.connectButton.setObjectName("connectButton")
        self.gridLayout.addWidget(self.connectButton, 3, 0, 1, 2)
        self.playerName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.playerName.setEnabled(False)
        self.playerName.setObjectName("playerName")
        self.gridLayout.addWidget(self.playerName, 1, 1, 1, 1)
        self.accessKey = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.accessKey.setEnabled(False)
        self.accessKey.setObjectName("accessKey")
        self.gridLayout.addWidget(self.accessKey, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setEnabled(False)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setEnabled(False)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.address = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.address.setEnabled(False)
        self.address.setObjectName("address")
        self.gridLayout.addWidget(self.address, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setEnabled(False)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.enableSettings = QtWidgets.QCheckBox(self.centralwidget)
        self.enableSettings.setGeometry(QtCore.QRect(240, 500, 321, 16))
        self.enableSettings.setObjectName("enableSettings")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(240, 600, 321, 41))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.height = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.height.setMinimum(1)
        self.height.setMaximum(100000)
        self.height.setProperty("value", 100)
        self.height.setObjectName("height")
        self.gridLayout_2.addWidget(self.height, 1, 3, 1, 1)
        self.xCoordLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.xCoordLabel.setObjectName("xCoordLabel")
        self.gridLayout_2.addWidget(self.xCoordLabel, 0, 0, 1, 1)
        self.yCoordLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.yCoordLabel.setObjectName("yCoordLabel")
        self.gridLayout_2.addWidget(self.yCoordLabel, 0, 1, 1, 1)
        self.heightLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.heightLabel.setObjectName("heightLabel")
        self.gridLayout_2.addWidget(self.heightLabel, 0, 3, 1, 1)
        self.widthLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.widthLabel.setObjectName("widthLabel")
        self.gridLayout_2.addWidget(self.widthLabel, 0, 2, 1, 1)
        self.xCoord = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.xCoord.setMaximum(100000)
        self.xCoord.setObjectName("xCoord")
        self.gridLayout_2.addWidget(self.xCoord, 1, 0, 1, 1)
        self.yCoord = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.yCoord.setMaximum(100000)
        self.yCoord.setObjectName("yCoord")
        self.gridLayout_2.addWidget(self.yCoord, 1, 1, 1, 1)
        self.width = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.width.setMinimum(1)
        self.width.setMaximum(100000)
        self.width.setProperty("value", 100)
        self.width.setObjectName("width")
        self.gridLayout_2.addWidget(self.width, 1, 2, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(580, 520, 291, 121))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.windowHandle = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.windowHandle.setObjectName("windowHandle")
        self.gridLayout_4.addWidget(self.windowHandle, 2, 1, 1, 1)
        self.captureFPS = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.captureFPS.setMinimum(1)
        self.captureFPS.setMaximum(120)
        self.captureFPS.setProperty("value", 60)
        self.captureFPS.setObjectName("captureFPS")
        self.gridLayout_4.addWidget(self.captureFPS, 0, 1, 1, 1)
        self.inGameThresholdLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.inGameThresholdLabel.setObjectName("inGameThresholdLabel")
        self.gridLayout_4.addWidget(self.inGameThresholdLabel, 4, 0, 1, 1)
        self.blackThresholdLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.blackThresholdLabel.setObjectName("blackThresholdLabel")
        self.gridLayout_4.addWidget(self.blackThresholdLabel, 3, 0, 1, 1)
        self.blackThreshold = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.blackThreshold.setMaximum(255)
        self.blackThreshold.setProperty("value", 25)
        self.blackThreshold.setObjectName("blackThreshold")
        self.gridLayout_4.addWidget(self.blackThreshold, 3, 1, 1, 1)
        self.captureFPSLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.captureFPSLabel.setObjectName("captureFPSLabel")
        self.gridLayout_4.addWidget(self.captureFPSLabel, 0, 0, 1, 1)
        self.inGameThreshold = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.inGameThreshold.setMaximum(1000000)
        self.inGameThreshold.setProperty("value", 15000)
        self.inGameThreshold.setObjectName("inGameThreshold")
        self.gridLayout_4.addWidget(self.inGameThreshold, 4, 1, 1, 1)
        self.windowHandleLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.windowHandleLabel.setObjectName("windowHandleLabel")
        self.gridLayout_4.addWidget(self.windowHandleLabel, 2, 0, 1, 1)
        self.sendFPSLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.sendFPSLabel.setObjectName("sendFPSLabel")
        self.gridLayout_4.addWidget(self.sendFPSLabel, 1, 0, 1, 1)
        self.sendFPS = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.sendFPS.setMinimum(1)
        self.sendFPS.setMaximum(120)
        self.sendFPS.setProperty("value", 20)
        self.sendFPS.setObjectName("sendFPS")
        self.gridLayout_4.addWidget(self.sendFPS, 1, 1, 1, 1)
        self.enableSettingsExpert = QtWidgets.QCheckBox(self.centralwidget)
        self.enableSettingsExpert.setGeometry(QtCore.QRect(580, 500, 241, 16))
        self.enableSettingsExpert.setObjectName("enableSettingsExpert")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(240, 520, 321, 41))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.captureWindowNameLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.captureWindowNameLabel.setObjectName("captureWindowNameLabel")
        self.gridLayout_5.addWidget(self.captureWindowNameLabel, 0, 0, 1, 1)
        self.captureWindowName = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.captureWindowName.setObjectName("captureWindowName")
        self.gridLayout_5.addWidget(self.captureWindowName, 1, 0, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(240, 570, 321, 21))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.showGrid = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        self.showGrid.setObjectName("showGrid")
        self.gridLayout_6.addWidget(self.showGrid, 0, 0, 1, 1)
        self.showStencil = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        self.showStencil.setObjectName("showStencil")
        self.gridLayout_6.addWidget(self.showStencil, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.preview, self.graphicsView)
        MainWindow.setTabOrder(self.graphicsView, self.address)
        MainWindow.setTabOrder(self.address, self.playerName)
        MainWindow.setTabOrder(self.playerName, self.accessKey)
        MainWindow.setTabOrder(self.accessKey, self.connectButton)
        MainWindow.setTabOrder(self.connectButton, self.enableSettings)
        MainWindow.setTabOrder(self.enableSettings, self.captureWindowName)
        MainWindow.setTabOrder(self.captureWindowName, self.showGrid)
        MainWindow.setTabOrder(self.showGrid, self.showStencil)
        MainWindow.setTabOrder(self.showStencil, self.xCoord)
        MainWindow.setTabOrder(self.xCoord, self.yCoord)
        MainWindow.setTabOrder(self.yCoord, self.width)
        MainWindow.setTabOrder(self.width, self.height)
        MainWindow.setTabOrder(self.height, self.enableSettingsExpert)
        MainWindow.setTabOrder(self.enableSettingsExpert, self.captureFPS)
        MainWindow.setTabOrder(self.captureFPS, self.windowHandle)
        MainWindow.setTabOrder(self.windowHandle, self.blackThreshold)
        MainWindow.setTabOrder(self.blackThreshold, self.inGameThreshold)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.status.setText(_translate("MainWindow", "Capture stopped"))
        self.preview.setText(_translate("MainWindow", "映像を更新する"))
        self.connectButton.setText(_translate("MainWindow", "接続"))
        self.label_6.setText(_translate("MainWindow", "キー:"))
        self.label_5.setText(_translate("MainWindow", "プレイヤー名:"))
        self.label_10.setText(_translate("MainWindow", "接続先:"))
        self.enableSettings.setText(_translate("MainWindow", "設定とテストを有効にする（非オンライン時のみ）"))
        self.xCoordLabel.setText(_translate("MainWindow", "X座標:"))
        self.yCoordLabel.setText(_translate("MainWindow", "Y座標:"))
        self.heightLabel.setText(_translate("MainWindow", "高さ:"))
        self.widthLabel.setText(_translate("MainWindow", "幅:"))
        self.inGameThresholdLabel.setText(_translate("MainWindow", "フィールド検出のしきい値:"))
        self.blackThresholdLabel.setText(_translate("MainWindow", "黒のしきい値:"))
        self.captureFPSLabel.setText(_translate("MainWindow", "キャプチャFPS:"))
        self.windowHandleLabel.setText(_translate("MainWindow", "ウィンドウハンドルを直接指定する (0で無効):"))
        self.sendFPSLabel.setText(_translate("MainWindow", "ネットワークFPS"))
        self.enableSettingsExpert.setText(_translate("MainWindow", "高度な設定を有効にする"))
        self.captureWindowNameLabel.setText(_translate("MainWindow", "次の名前で始まるウィンドウをキャプチャする:"))
        self.showGrid.setText(_translate("MainWindow", "グリッドを表示"))
        self.showStencil.setText(_translate("MainWindow", "ガイドを表示"))
